# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af62f619c7f86f04c1ea14b63aac78f7013a48100e2ba1b2c6751b317dc7a111909c32c0b263574ec6b890f88d66306b84b9642bcaffe8785013066093fb39cc

test:
  secret_key_base: ac493ab827857e228fea5ecadc3eb60ea282411b00fe033e6b6ab6a4f8ccf1944d941a33adaf2f6b54b56cd1f047eb70f82c426c7adff0600d64c0e06b1f5b19

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
